//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockOnlineEntities : DbContext
    {
        public StockOnlineEntities()
            : base("name=StockOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_BasicInfo> Tb_BasicInfo { get; set; }
        public virtual DbSet<Tb_Category> Tb_Category { get; set; }
        public virtual DbSet<Tb_Company> Tb_Company { get; set; }
        public virtual DbSet<Tb_Department> Tb_Department { get; set; }
        public virtual DbSet<Tb_Employee> Tb_Employee { get; set; }
        public virtual DbSet<Tb_EvaluatedFactor> Tb_EvaluatedFactor { get; set; }
        public virtual DbSet<Tb_EvaluatedPeople> Tb_EvaluatedPeople { get; set; }
        public virtual DbSet<Tb_EvaluatedPeopleDetail> Tb_EvaluatedPeopleDetail { get; set; }
        public virtual DbSet<Tb_EvaluatedPostion> Tb_EvaluatedPostion { get; set; }
        public virtual DbSet<Tb_EvaluatingMaster> Tb_EvaluatingMaster { get; set; }
        public virtual DbSet<Tb_FileInfo> Tb_FileInfo { get; set; }
        public virtual DbSet<Tb_IncentiveObject> Tb_IncentiveObject { get; set; }
        public virtual DbSet<Tb_Measure> Tb_Measure { get; set; }
        public virtual DbSet<Tb_MeasurePartner> Tb_MeasurePartner { get; set; }
        public virtual DbSet<Tb_MeasureProgram> Tb_MeasureProgram { get; set; }
        public virtual DbSet<Tb_Mechanism> Tb_Mechanism { get; set; }
        public virtual DbSet<Tb_Member> Tb_Member { get; set; }
        public virtual DbSet<Tb_News> Tb_News { get; set; }
        public virtual DbSet<Tb_PeopleScore> Tb_PeopleScore { get; set; }
        public virtual DbSet<Tb_Post> Tb_Post { get; set; }
        public virtual DbSet<Tb_PostionScore> Tb_PostionScore { get; set; }
        public virtual DbSet<Tb_PostionScoreDetail> Tb_PostionScoreDetail { get; set; }
        public virtual DbSet<Tb_Quota> Tb_Quota { get; set; }
        public virtual DbSet<Tb_Shareholde> Tb_Shareholde { get; set; }
        public virtual DbSet<Tb_ShareHolding> Tb_ShareHolding { get; set; }
        public virtual DbSet<Tb_Structure> Tb_Structure { get; set; }
    }
}
