//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Employee
    {
        public System.Guid EmployeeID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid Creator { get; set; }
        public Nullable<System.DateTime> LastModiTime { get; set; }
        public Nullable<System.Guid> LastModifier { get; set; }
        public bool IsDel { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public Nullable<System.Guid> PostID { get; set; }
        public byte[] Avatar { get; set; }
        public string Mobile { get; set; }
        public string JobAge { get; set; }
        public string Rank { get; set; }
        public string AnnualSalary { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public Nullable<System.Guid> EnterpriseID { get; set; }
        public string EmployeeNum { get; set; }
    }
}
