//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ShareHolding
    {
        public System.Guid Id { get; set; }
        public System.Guid EnterpriseID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public int HoldingValue { get; set; }
        public HoldingMethods HoldingMethod { get; set; }
        public decimal PositonRate { get; set; }
        public decimal PeopleRate { get; set; }
        public int EvaluatingMethod { get; set; }
        public int EvalutatingStep { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid Creator { get; set; }
        public bool IsDel { get; set; }
        public System.Guid LastModifier { get; set; }
        public System.DateTime LastModiTime { get; set; }
        public int EvaluatingType { get; set; }
        public Nullable<System.DateTime> EvaluateDate { get; set; }
    }
}
