//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Shareholde
    {
        public System.Guid ShareholdeID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid Creator { get; set; }
        public Nullable<System.DateTime> LastModiTime { get; set; }
        public Nullable<System.Guid> LastModifier { get; set; }
        public bool IsDel { get; set; }
        public string HoldMechanism { get; set; }
        public Nullable<decimal> HoldPercent { get; set; }
        public Nullable<int> HoldCoun { get; set; }
        public Nullable<System.Guid> HoldCategoryID { get; set; }
        public string HoldCategoryName { get; set; }
        public string HoldName { get; set; }
        public Nullable<System.Guid> HoldAttributeID { get; set; }
        public string HoldAttributeName { get; set; }
        public bool IsShares { get; set; }
        public Nullable<int> SharesCount { get; set; }
        public Nullable<System.DateTime> ShareTime { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public Nullable<int> ClassLayer { get; set; }
        public Nullable<System.Guid> StructureID { get; set; }
    }
}
